server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://admin:admin123@eureka-server:7001/eureka/
  instance:
    instance-id: webproject
    prefer-ip-address: true 
    
spring:
  application:
    name:  webproject
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://111.207.49.168:3306/fcspp?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

info: 
  app.name: chinasofti-microserver
  company.name: www.chinasofti.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$



